name: "github runner test"
on:
  workflow_dispatch:
    inputs:
      name: 
        description: "display name"
        required: true
        type: choice
        default: "venkat"
        options:
          - krishnan
          - sparrow
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: display message
        run: echo "Hello ${{ github.event.inputs.name }}""